* Made the progress and error messages more verbose. <br> * Fixed a bug in the error reporting, where "RunSanityTests" would always appear instead of the literal command-line text we fed to the shell.

diff --git a/rvm/regression/NightSanityDriver b/rvm/regression/NightSanityDriver
--- a/rvm/regression/NightSanityDriver
+++ b/rvm/regression/NightSanityDriver
@@ -70,4 +70,10 @@ done
 
 $succeed_immediately
 
-awk "{ print \"$RVM_ROOT/rvm/regression/RunSanityTests -configurations \" \$0 \" $ADDED || echo >&2 'Running the test $0 died.'\" }" "${DRIVER}" | sh -s
+awk "{ 
+print \"echo 'About to launch RunSanityTests -configurations \" \$0 \" $ADDED'\" ;
+print \"$RVM_ROOT/rvm/regression/RunSanityTests -configurations \" \$0 \" $ADDED || { \n\
+     code=\$? ; \n\
+     echo >&2 'Running the test \" \$0 \" died with error code \$code.' ; \n\
+     echo >&2 'Test run as:   RunSanityTests -configurations \" \$0 \" $ADDED' ;  } \"
+}" "${DRIVER}" | sh -s
