Merged in the changes from Bash_Debug_BRANCH.  We shall see how the nightly builds go.

diff --git a/rvm/regression/night-sanity-build b/rvm/regression/night-sanity-build
--- a/rvm/regression/night-sanity-build
+++ b/rvm/regression/night-sanity-build
@@ -1,34 +1,72 @@
-#!/bin/ksh
+#! /bin/bash
 #
-# (C) Copyright IBM Corp. 2001
+# (C) Copyright IBM Corp. 2001, 2003
 #
 # $Id$
 #
 # @author Julian Dolby
+#
+# @modified Steven Augart
 
 # This script will build the boot images
 # It then signals another script, night-sanity-run to perform the runs.
 
+ME="${0##*/}"
+function usage() {
+    echo >&2 "Usage: $ME <build-configuration>"
+    [ "$*" ] && echo >&2 "$ME: $*"
+    exit 1
+}
+function croak() {
+    exec >&2			# stderr
+    if [ "$*" ]; then
+	echo "$ME: $*"
+    fi
+    echo "$ME: Aborting Execution; goodbye!"
+    exit 2
+}
+
+(( $# == 1 )) || usage "You gave $# arguments; I expected exactly 1 argument."
+configuration="$1"
 export PATH=$PATH:.
 
+config_fullpath=$RVM_ROOT/rvm/regression/config/$configuration
+[ "$RVM_ROOT" ] || croak "RVM_ROOT must be set, but isn't."
+[[ -f "${config_fullpath}" ]] || croak "Cannot find $configuration in the directory $RVM_ROOT/rvm/regression/config/"
+
+[[ -d $RVM_ROOT/results ]] || croak "The directory $RVM_ROOT/results does not exist; I have no place to write my log files."
 # Where the fullshadow and other verbose output are placed, not mailed
-export VERBOSE_LOG=$RVM_ROOT/results/verbose.log
+export VERBOSE_LOG="$RVM_ROOT"/results/verbose.log
 
 # Where the build output is placed, this is mailed when the tests failed
-export BUILD_LOG=$RVM_ROOT/results/build.log
+export BUILD_LOG="$RVM_ROOT"/results/build.log
+
+trap "echo >&2 $ME: Aborting execution early due to an error while running some program" ERR
+set -e
 
 umask 022
 
+echo "Any further output will go to $BUILD_LOG"
+exec >> $BUILD_LOG 2>&1
+
 # build the boot images, but don't run any tests
-echo "Building the boot images\n" >> $BUILD_LOG
-
-$RVM_ROOT/rvm/regression/NightSanityDriver -common "-images $RVM_ROOT/images -result $RVM_ROOT/results -norun -wait sem" -config $1 >> $BUILD_LOG 2>> $BUILD_LOG
-
-# build javadoc for FullAdaptiveSemispace image.
-. $RVM_ROOT/images/FullAdaptiveSemiSpace/jbuild.environment
-$RVM_ROOT/rvm/bin/jdoc.sh $RVM_ROOT/doc/api both >> $BUILD_LOG 2>> $BUILD_LOG
-
-echo "\n\nBuild complete, builder script exiting.\n" >> $BUILD_LOG
+images="$RVM_ROOT/images"
+echo "Building the boot images, in $images"
+results="$RVM_ROOT/results"
+echo "Results go into $results";
+echo "Using the configuration $configuration, in $config_fullpath"
 
 
+$RVM_ROOT/rvm/regression/NightSanityDriver -common "-images $images -result $results -norun -wait sem" -config "${configuration}" || croak "Running NightSanityDriver to build (-norun) failed miserably."
 
+echo "OK, now we will try to build the javadoc for the FullAdaptiveSemiSpace image"
+dir="$RVM_ROOT/images/FullAdaptiveSemiSpace"
+if [[ ! -d $dir ]]; then
+    echo "$ME: It looks as if you didn't make a FullAdaptiveSemiSpace build.  We'll skip jdoc.sh."
+else
+    je="$dir/jbuild.environment"
+    . $je || croak "Unable to load $je"
+    "$RVM_ROOT/rvm/bin/jdoc.sh" "$RVM_ROOT/doc/api" both || croak "Trouble running jdoc.sh; sorry!"
+fi
+
+echo -e "\n\nBuild complete, builder script exiting.\n"
diff --git a/rvm/regression/night-sanity-run b/rvm/regression/night-sanity-run
--- a/rvm/regression/night-sanity-run
+++ b/rvm/regression/night-sanity-run
@@ -1,10 +1,11 @@
-#!/bin/ksh
+#! /bin/bash
 #
-# (C) Copyright IBM Corp. 2001
+# (C) Copyright IBM Corp. 2001, 2003
 #
 # $Id$
 #
 # @author Julian Dolby
+# @modified Steven Augart
 
 # This script will run sanity and performance tests.  
 # It assumes the boot images have 
@@ -49,8 +50,8 @@ export PERF_LOG=$RVM_ROOT/results/performance.log
 umask 022
 
 # Determine architecture and set number of processors accordingly
-ARCH=`uname`
-if [[ $ARCH = 'Linux' ]] then
+ARCH=$(uname)
+if [[ $ARCH = 'Linux' ]]; then
   NUM_PROCS=4
 else
   NUM_PROCS=2
@@ -63,70 +64,98 @@ chmod 755 $RUN_LOG
 # cd to the SHADOW to get things started
 cd $RVM_ROOT
 
+dry_run=""
+if [[ $1 = "-dry-run" ]]; then
+    dry_run="-succeed-immediately";
+    shift;
+fi
+
+sanity_cfg="$1";
 # sanity runs
-echo "\n\nRunning the sanity tests as specified in $CONFIG_DIR/$1 \n" >> $RUN_LOG
+echo -e "\n\nRunning the sanity tests as specified in $CONFIG_DIR/$sanity_cfg \n" >> $RUN_LOG
 
-$RVM_ROOT/rvm/regression/NightSanityDriver -common "-images $RVM_ROOT/images -result $RVM_ROOT/results/sanity -nobuild -numprocs $NUM_PROCS -wait sem" -config $1 >> $RUN_LOG 2>> $RUN_LOG
+$RVM_ROOT/rvm/regression/NightSanityDriver $dry_run -common "-images $RVM_ROOT/images -result $RVM_ROOT/results/sanity -nobuild -numprocs $NUM_PROCS -wait sem" -config $sanity_cfg >> $RUN_LOG 2>> $RUN_LOG
 
-# performance runs
-echo "\n\nRunning the performance tests as specified in $CONFIG_DIR/$2\n" >> $RUN_LOG
 
-$RVM_ROOT/rvm/regression/NightSanityDriver -common "-images $RVM_ROOT/images -result $RVM_ROOT/results/performance -nobuild -numprocs $NUM_PROCS -wait sem -performance $PERF_LOG" -config $2 >> $RUN_LOG 2>> $RUN_LOG
+if (( $# < 2 )); then
+    echo -e "\n\nWe will not run any performance tests; none requested.\n" >> $RUN_LOG
+    echo "Not running performance tests, since none requested." >> $PERF_LOG
+    perf_cfg=""
+else
+    perf_cfg="$2"
+    # performance runs
+    echo -e "\n\nRunning the performance tests as specified in $CONFIG_DIR/$perf_cfg\n" >> $RUN_LOG
+
+    $RVM_ROOT/rvm/regression/NightSanityDriver $dry_run -common "-images $RVM_ROOT/images -result $RVM_ROOT/results/performance -nobuild -numprocs $NUM_PROCS -wait sem -performance $PERF_LOG" -config $perf_cfg >> $RUN_LOG 2>> $RUN_LOG
+fi
 
 # measure compilation time
-echo "\n\nRunning the measure compilation time tests\n" >> $RUN_LOG
+echo -e "\n\nRunning the measure compilation time tests\n" >> $RUN_LOG
 
 export  MEASURE_COMPILATION_DIR=$RVM_ROOT/results/measureCompilation
 mkdir -p $MEASURE_COMPILATION_DIR
 
-$RVM_ROOT/rvm/regression/NightSanityDriver -common "-images $RVM_ROOT/images -result $MEASURE_COMPILATION_DIR -nobuild -numprocs $NUM_PROCS -measureCompilation -wait sem -rc-args -X:measureCompilation=true -use-opt-levels 'O0 O1 O2'"  -config night-sanity-measure-compilation-config >> $RUN_LOG 2>> $RUN_LOG
+$RVM_ROOT/rvm/regression/NightSanityDriver $dry_run -common "-images $RVM_ROOT/images -result $MEASURE_COMPILATION_DIR -nobuild -numprocs $NUM_PROCS -measureCompilation -wait sem -rc-args -X:measureCompilation=true -use-opt-levels 'O0 O1 O2'"  -config night-sanity-measure-compilation-config >> $RUN_LOG 2>> $RUN_LOG
 
 # Fix the permission bits because umask doesn't seem to be working correctly
 echo "fixing permission bits" >> $RUN_LOG
 chmod -R 755 $RVM_ROOT 2>> $RUN_LOG
 
 # Archive result files and performance results
-echo "Archiving results into $ARCHIVE\n" >> $RUN_LOG
-tarfile=$ARCHIVE/archive.`date +"%A"`.`uname`.tar.gz
-($RVM_ROOT/rvm/regression/copyBuildTraceFiles $RVM_ROOT/images $RVM_ROOT/results; find $RVM_ROOT/results -name cp -exec rm -rf {} \;; cd $RVM_ROOT; $GNU_TAR czvf $tarfile results) >> $VERBOSE_LOG 2>> $VERBOSE_LOG
 
-echo "sending tar to dW" >> $VERBOSE_LOG 2>> $VERBOSE_LOG
-cd $RVM_ROOT/sanityResults
-TRANSFER_FILE_NAME=`date +"%A"`.`uname`.tar.gz
-cp $tarfile $TRANSFER_FILE_NAME
-$CVS add $TRANSFER_FILE_NAME >> $VERBOSE_LOG 2>> $VERBOSE_LOG
-$CVS commit -m "night sanity" $TRANSFER_FILE_NAME >> $VERBOSE_LOG 2>> $VERBOSE_LOG
-rm -f $TRANSFER_FILE_NAME
-mv CVS/Entries CVS/tmp
-grep -v $TRANSFER_FILE_NAME < CVS/tmp > CVS/Entries
-rm -f CVS/tmp
-cd $RVM_ROOT
+if [[ ! -d $ARCHIVE ]]; then
+    echo >> $RUN_LOG "No archive directory named $ARCHIVE exists; skipping archiving."
+else
+    echo -e "Archiving results into $ARCHIVE\n" >> $RUN_LOG
+    tarfile=$ARCHIVE/archive.`date +"%A"`.${ARCH}.tar.gz
+    ($RVM_ROOT/rvm/regression/copyBuildTraceFiles $RVM_ROOT/images $RVM_ROOT/results; find $RVM_ROOT/results -name cp -exec rm -rf {} \;; cd $RVM_ROOT; $GNU_TAR czvf $tarfile results) >> $VERBOSE_LOG 2>> $VERBOSE_LOG
 
+    echo "sending tar to dW" >> $VERBOSE_LOG 2>> $VERBOSE_LOG
+    if ! cd $RVM_ROOT/sanityResults; then
+	echo >> $RUN_LOG "No directory or trouble with $RVM_ROOT/sanityResults; won't send tar to dW.";
+    else
+	TRANSFER_FILE_NAME=`date +"%A"`.${ARCH}.tar.gz
+	cp $tarfile $TRANSFER_FILE_NAME
+	$CVS add $TRANSFER_FILE_NAME >> $VERBOSE_LOG 2>> $VERBOSE_LOG
+	$CVS commit -m "night sanity" $TRANSFER_FILE_NAME >> $VERBOSE_LOG 2>> $VERBOSE_LOG
+	rm -f $TRANSFER_FILE_NAME
+	mv CVS/Entries CVS/tmp
+	grep -v $TRANSFER_FILE_NAME < CVS/tmp > CVS/Entries
+	rm -f CVS/tmp
+	cd $RVM_ROOT
+    fi
+fi
 
 # determine how many ran, failed, and passed, then build a summary line
 numran=`grep "sane" $RUN_LOG | wc -l`
 numfailed=`grep "You are NOT sane" $RUN_LOG | wc -l`
 numpassed=`grep "You are sane" $RUN_LOG | wc -l`
-echo "Ran $numran, Passed \t$numpassed, Failed \t$numfailed" >> $RUN_LOG
+echo -e "Ran $numran, Passed \t$numpassed, Failed \t$numfailed" >> $RUN_LOG
 
-if [[ $numran -eq 0 ]] then
+if [[ $numran -eq 0 ]]; then
   echo "*** No tests were run! *** " >> $MSG
-  echo "There was probably an error in building the boot images.\n\n" >> $MSG
+  echo -e "There was probably an error in building the boot images.\n\n" >> $MSG
 else
 #  Build the summary line
-  echo "Ran \t$numran \nPassed \t$numpassed\nFailed \t$numfailed \n\n" >> $MSG
+  echo -e "Ran \t$numran \nPassed \t$numpassed\nFailed \t$numfailed \n\n" >> $MSG
 fi
 
-# Also report the number of javadoc errors
-numjavadocErrors=`grep warning $RVM_ROOT/doc/api/javadoc.out | sort | uniq | wc -l`
-if [[ $numjavadocErrors -eq 0 ]] then 
-  echo "There were no javadoc errors." >> $MSG
-else 
-  echo "There were $numjavadocErrors javadoc errors." >> $MSG
+javadoc_out="$RVM_ROOT/doc/api/javadoc.out"
+if [[ ! -f $javadoc_out ]]; then
+    echo "No javadoc results are available; the file $javadoc_out isn't there" >>$MSG
+    numjavadocErrors=0
+else
+    # Also report the number of javadoc errors
+    numjavadocErrors=$(grep warning $javadoc_out | sort | uniq | wc -l)
+    if [[ $numjavadocErrors -eq 0 ]]; then 
+      echo "There were no javadoc errors." >> $MSG
+    else 
+      echo "There were $numjavadocErrors javadoc errors." >> $MSG
+    fi
 fi
 
 # Print some details on the failures
-if [[ $numfailed -gt 0 ]] then
+if [[ $numfailed -gt 0 ]]; then
   echo >> $MSG
   echo Failure Details >> $MSG
   echo --------------- >> $MSG
@@ -137,7 +166,7 @@ if [[ $numfailed -gt 0 ]] then
     >> $MSG
 fi
 
-if [[ $numjavadocErrors -gt 0 && $numjavadocErrors -lt 50 ]] then 
+if [[ $numjavadocErrors -gt 0 && $numjavadocErrors -lt 50 ]]; then 
   echo >> $MSG
   echo Javadoc Errors >> $MSG
   echo -------------- >> $MSG
@@ -145,9 +174,13 @@ if [[ $numjavadocErrors -gt 0 && $numjavadocErrors -lt 50 ]] then
 fi
 
 # Describe where the information can be found
-echo "\nOutput of this run is available (for 24 hours) at http://www-124.ibm.com/developerworks/oss/jikesrvm/sanityResults/$TRANSFER_FILE_NAME" >> $MSG
-echo "  Sanity tests are specified in $CONFIG_DIR/$1" >> $MSG
-echo "  Performance tests are specified in $CONFIG_DIR/$2" >> $MSG
+echo -e "\nOutput of this run is available (for 24 hours) at http://www-124.ibm.com/developerworks/oss/jikesrvm/sanityResults/$TRANSFER_FILE_NAME" >> $MSG
+echo "  Sanity tests are specified in $CONFIG_DIR/$sanity_cfg" >> $MSG
+if [ "$perf_cfg" ]; then
+    echo "  Performance tests are specified in $CONFIG_DIR/$perf_cfg" >> $MSG
+else
+    echo "  No performance tests were run." >> $MSG
+fi
 
 # Grab the bottom line performance and place it in a more visible place
 echo >> $MSG
@@ -162,20 +195,20 @@ echo ----------------------------- >> $MSG
 $AWK -f $RVM_ROOT/rvm/regression/PerformanceVerbose.awk -v targetBench=SPECjvm98 $RVM_ROOT/results/performance.log >> $MSG
 
 # gather measure compilation results
-echo "\n\n Opt Level 0 compilation breakdown for SPECjvm98 size 100\n" >> $MSG
+echo -e "\n\n Opt Level 0 compilation breakdown for SPECjvm98 size 100\n" >> $MSG
 $AWK -f $RVM_ROOT/rvm/regression/findMeasureCompilationResults.awk $MEASURE_COMPILATION_DIR/rvm/regression/tests/SPECjvm98/out.SpecApplication.FastSemiSpace.O0.?proc.raw >> $MSG
 #
-echo "\n\n Opt Level 1 compilation breakdown for SPECjvm98 size 100\n" >> $MSG
+echo -e "\n\n Opt Level 1 compilation breakdown for SPECjvm98 size 100\n" >> $MSG
 $AWK -f $RVM_ROOT/rvm/regression/findMeasureCompilationResults.awk $MEASURE_COMPILATION_DIR/rvm/regression/tests/SPECjvm98/out.SpecApplication.FastSemiSpace.O1.?proc.raw >> $MSG
 #
-echo "\n\n Opt Level 2 compilation breakdown for SPECjvm98 size 100\n" >> $MSG
+echo -e "\n\n Opt Level 2 compilation breakdown for SPECjvm98 size 100\n" >> $MSG
 $AWK -f $RVM_ROOT/rvm/regression/findMeasureCompilationResults.awk $MEASURE_COMPILATION_DIR/rvm/regression/tests/SPECjvm98/out.SpecApplication.FastSemiSpace.O2.?proc.raw >> $MSG
 
 # Finally!  Send the mail message to those who care
 # echo "mailing status to $RESULT_MAILING_LIST"
 cat $MSG >> $RUN_LOG
 
-if [[ $numran -gt 0 && $numfailed -eq 0 ]] then
+if [[ $numran -gt 0 && $numfailed -eq 0 ]]; then
   cat $MSG | mail -s "[$ARCH] regression SUCCEEDED" $RESULT_MAILING_LIST 
 else
   cat $MSG | mail -s "[$ARCH] regression FAILED $numfailed tests" $RESULT_MAILING_LIST
@@ -185,7 +218,7 @@ fi
 # Check that files contain an @author tag, a CVS Id tag, and a Copyright notice.
 # Only run on one machine: currently AIX
 #
-if [[ $ARCH = 'AIX' ]] then
+if [[ $ARCH = 'AIX' ]]; then
   export CHECK_DIR=$RVM_ROOT/results
 
   # Check files
@@ -193,17 +226,17 @@ if [[ $ARCH = 'AIX' ]] then
  
   # Email results 
   # Only email to volations to $RESULT_MAILING_LIST
-  if [[ -s $CHECK_DIR/noAuthor.rvm ]] then
+  if [[ -s $CHECK_DIR/noAuthor.rvm ]]; then
    cat $CHECK_DIR/noAuthor.rvm    | mail -s "files without an @author tag"     $RESULT_MAILING_LIST
 #  else
 #   echo " " | mail -s "no files without an @author tag"     pfs 
   fi
-  if [[ -s $CHECK_DIR/noId.rvm ]] then
+  if [[ -s $CHECK_DIR/noId.rvm ]]; then
     cat $CHECK_DIR/noId.rvm       | mail -s "files without a CVS Id tag"       $RESULT_MAILING_LIST
 #  else
 #    echo " " | mail -s "no files without a CVS Id tag"       pfs 
   fi
-  if [[ -s $CHECK_DIR/noCopyright.rvm ]] then
+  if [[ -s $CHECK_DIR/noCopyright.rvm ]]; then
     cat $CHECK_DIR/noCopyright.rvm| mail -s "files without a Copyright notice" $RESULT_MAILING_LIST
 #  else
 #    echo " " | mail -s "no files without a Copyright notice" pfs 
