We now require GNU Classpath 0.08.

diff --git a/rvm/bin/jBuildClasspathJar b/rvm/bin/jBuildClasspathJar
--- a/rvm/bin/jBuildClasspathJar
+++ b/rvm/bin/jBuildClasspathJar
@@ -97,7 +97,7 @@ fi
 if [[ ! -e $DEST_DIR/classpath/TODO ]]; then
     if [[ $USE_LOCAL_CLASSPATH != "no" ]]; then
 	echo >&2 "Please download GNU Classpath and unpack it in $DEST_DIR"
-	echo >&2 "(You should use classpath-0.07 or newer for best results)"
+	echo >&2 "(Classpath 0.08 or newer is required)"
 	exit 1
     fi
     echo "Downloading GNU Classpath"
