<ul> <li>Doc fixes -- added several paragraphs of comments <li>Support building with Jikes 1.20, 1.21, 1.22, and CVS head, although we print a CAUTION message that we haven't run a rigorous regression test on Jikes RVM built with those versions.  In using those versions of Jikes, we do not specify the +U (dependency-checking) flag.
<li>Getting an empty string in response to running " -version"
is now a fatal error.

</ul>

diff --git a/rvm/bin/jconfigure b/rvm/bin/jconfigure
--- a/rvm/bin/jconfigure
+++ b/rvm/bin/jconfigure
@@ -390,10 +390,17 @@ function setSomeFromPath () {
 
 
 
+## Set JIKES, the path for the Jikes java-to-byte-code compiler.  
+## A necessary part of the build process.  We only run JIKES on the host.
+## Check the version of Jikes, and print appropriate warning messages.
+##
+## We also set the following variables that are used elsewhere:
+##    host_jikes_version   
+##    copy_MMTk_directories_too
+##    jikes_dependency_flag
+## and set the default value for the following configuration variable:
+##    JIKES_WARNING_FLAGS
 function on_host_set_JIKES_test_Jikes_version () {
-    # Set JIKES, the path for the Jikes java-to-byte-code compiler.  
-    # A necessary part of the build process.  We only run JIKES 
-    # on the host.
     if [[ $CURRENT_CONFIG_FILE = $RVM_HOST_CONFIG ]]	\
 	&& ! [[ ${JIKES-} ]]				\
 	&& ! export JIKES=$(type -p jikes)
@@ -432,6 +439,10 @@ function on_host_set_JIKES_test_Jikes_version () {
 	    exit 2
 	fi
 	local -i bad_byte_code=0
+	## unregressed indicates a version that can run "Hello, World", but has
+	## not been through a full nightly Jikes RVM regression test.
+	local -i unregressed=0
+	local -r known_good="1.13, 1.18, and 1.19"
 	case "$jikes_msg" in
 	    *"Version 1.13"*)
 		host_jikes_version=1.13 
@@ -479,31 +490,43 @@ function on_host_set_JIKES_test_Jikes_version () {
 	    
 	    *"Version 1.20"*)
 		host_jikes_version=1.20
-		bad_byte_code=1	# Verified by Steve Augart...
+		bad_byte_code=0	# Verified by Steve Augart, at least as far as
+				# running "Hello, World" works.
+		unregressed=1
 		jikes_dependency_flag= # +U triggers a Jikes assertion.
+		# This will reduce the warnings down to a so-so level,
+		# but it's not enough to completely eliminate them.
+		# Some of them are legitimate, though.
+		# JIKES_WARNING_FLAGS='+Pno-switchcheck +Pno-shadow'
 		JIKES_WARNING_FLAGS=-nowarn # Still too many style warnings.
 		;;
 	    
  	    *"Version 1.21"*)
  		host_jikes_version=1.21
-		bad_byte_code=1	# Verified by Steve Augart...
+		bad_byte_code=0	# Verified by Steve Augart, at least as far as
+				# running "Hello, World" works.
+		unregressed=1
 		jikes_dependency_flag= # +U triggers a Jikes assertion.
  		JIKES_WARNING_FLAGS=-nowarn # Still too many style warnings.
  		;;
 	    
 	    *"Version 1.22"*)
 		host_jikes_version=1.22 
-		bad_byte_code=1	# Verified by Steve Augart...
+		bad_byte_code=0	# Verified by Steve Augart, at least as far as
+				# running "Hello, World" works.
+		unregressed=1
 		jikes_dependency_flag= # +U triggers a Jikes assertion.
 		JIKES_WARNING_FLAGS=-nowarn
 		;;
 	    
-	    "") show_mesg >&2 "WARNING: I can not get a version message from the Jikes java-to-byte-code compiler; something may be badly wrong. Continuing anyway.  I tried using this invocation of Jikes:
-   \"${JIKES} -version\"" 
-		host_jikes_version=UNAVAILABLE-OR-BAD
+	    "") show_mesg >&2 "ERROR: I did not get any version message from the Jikes java-to-byte-code compiler; something may be badly wrong.  I tried using this invocation of Jikes:
+   \"${JIKES} -version\""
+		show_mesg >&2 "This looks bad; I am giving up.  
+  The likely offending configuration file is  \"${CURRENT_CONFIG_FILE}\""
+		exit 2
 		;;
 	    *)
-		show_mesg >&2 "WARNING: \"${JIKES}\" is a version of Jikes that may not be able to compile Jikes RVM -- the known good versions are 1.13, 1.18, and 1.19.  Your version gives me the message:"
+		show_mesg >&2 "CAUTION: \"${JIKES}\" is a version of Jikes that has not been tested against Jikes RVM -- the known good versions are ${known_good}.  Your version gives me the message:"
 		## If we can't find a line with the string Version, then
 		## print the whole message.
 		( echo "$jikes_msg" | ${FGREP-fgrep} "Version" \
@@ -514,9 +537,10 @@ function on_host_set_JIKES_test_Jikes_version () {
     #     echo "JIKES VERSION: $jikes_version"
 
 	if (( bad_byte_code )); then
-	    show_mesg >&2 "WARNING: Jikes Version $host_jikes_version is known to have generated bad byte code when compiling Jikes RVM.  If you're lucky, the failure will be spectacular.   If you're not, it will waste a lot of your time.  PLEASE reconsider."
+	    show_mesg >&2 "WARNING: Jikes Version $host_jikes_version is known to have generated bad byte code when compiling Jikes RVM.  If you're lucky, the failure will be spectacular.   If you're not, it will waste a lot of your time.  PLEASE consider using one of the known good versions, ${known_good}."
+	elif (( unregressed )); then
+	    show_mesg >&2 "CAUTION: Versions of Jikes RVM compiled with Jikes Version $host_jikes_version have not gone through a rigorous regression test, although we do not have evidence of problems, and they do run \"Hello, World\" OK.  This message will be removed once someone runs a rigorous regression test  (perhaps you'd like to be the one to run it and to remove this message?)"
 	fi
-
     fi
 }
 
@@ -813,10 +837,12 @@ function load_config_file () {
 # If $host_jikes_version is the empty string, that means we have never 
 # tried to auto-detect the host's Jikes version.  We'll only auto-detect
 # the host's jikes version once.
+#
+# It may be a numeric string, such as 1.13 or 1.22, or it may be "UNKNOWN"
 declare host_jikes_version=""
 
-# Start off blank.  These all get set at the same time that we
-# set host_jikes_version
+# Start off blank.  These all get set at the same time that we set 
+# host_jikes_version
 
 # Use Java warnings?
 ## This would need to be set independently for the host and target,
@@ -824,12 +850,36 @@ declare host_jikes_version=""
 ## This default can be overridden by the config file(s) or by -D arguments
 ## to jconfigure.
 declare JIKES_WARNING_FLAGS=
-declare jikes_dependency_flag=
+
+
+
+# The +U option is used to ensure that the source code in files in
+# vm/libSupport/* (the VM* classes we have for GNU classpath
+# compatibility) actually get seen when you recompile.  Otherwise,
+# Jikes sees the precompiled VM* files in the GNU Claspath Jar, and
+# doesn't see our versions that are supposed to supersede them.
+# 
+# We make this resettable for a couple of reasons.  First, since some
+# versions of Jikes will generate an assertion failure when they read
+# the bytecode generated for some of the files in GNU Classpath.
+# Second, so that we can use Java compilers other than Jikes.
+# TODO: The need for the dependency flag can probably be fixed by
+# explicitly invoking jikes/javac on each of those files.  Or some
+# other piece of scripting that made sure that our source files for
+# java.* are found instead of the class files in the jar.
+declare jikes_dependency_flag=+U
 JAVAC_WARNING_FLAGS=-nowarn
 
 ## Set this to 1 if we find that the host is using Jikes 1.13, which does not
-## support the -sourcepath argument.
+## support the -sourcepath argument, or (TODO) if we're building with
+## some other compiler that also does not support -sourcepath. 
 declare -i copy_MMTk_directories_too=0
+
+    
+## An alternative we can use if we are dealing with a complier other
+## than Jikes.  TODO; currently unused.
+declare -i all_sources_are_top_level=0
+
 
 load_config_file "${RVM_HOST_CONFIG}"
 
@@ -959,7 +1009,14 @@ BOOTER_STR=${BUILD_DIRECTORY_STR}/JikesRVM
 # Variables to allow configuration files to alter the list of
 # directories, primordials, exclusions and top level sources.
 #
-CONF_SPECIFIC_SOURCES_LIST=""
+# All of these are whitespace-separated lists (newlines, spaces, 
+# or TAB characters are all OK)
+CONF_SPECIFIC_SOURCES_LIST=""	# CONF_SPECIFIC_SOURCES_LIST is misnamed.  It 
+				# is actually a list of DIRECTORIES that will 
+				# be scanned by the preprocessor, and whose 
+				# contents will be copied into the same place 
+				# where we stick the other preprocessed 
+				# Jikes RVM source files.		
 CONF_SPECIFIC_PRIMORDIALS_LIST=""
 CONF_SPECIFIC_EXCLUSIONS_LIST=""
 CONF_SPECIFIC_TOP_LEVEL_SOURCES=""
@@ -2588,13 +2645,13 @@ function emitCompiler () {
 	echo -n "\${ME}: "
 	[ ! "\$VFLAG\$XFLAG" ] || set \$VFLAG \$XFLAG
 
+	chdir $CLASSES_DIRECTORY_STR
 	if [[ \$CLEAN_FLAG ]]; then
 	    open_paren 'cleaning .class files'
-	    cd ${CLASSES_DIRECTORY_STR}
 	    # This avoids any limits on the size of the command-line arguments.
 	    # 'echo' is a bash builtin, and as such is unaffected by such O/S 
 	    # limits. 
-	    echo *.class | \$XARGS rm -f
+	    run-evaled echo \\\*.class \| \$XARGS rm -f
 	    touch ${CLASSES_INVALID_STR} 
 	    close_paren "classes cleaned "
 	    trap "" EXIT
@@ -2603,30 +2660,52 @@ function emitCompiler () {
 EOF
     # Generate classes
     #
-    TOP_LEVEL_SOURCES="Dummy.java"
-    if (( RVM_WITH_OPT_COMPILER )); then
-	TOP_LEVEL_SOURCES="${TOP_LEVEL_SOURCES} OptDummy.java"
-    fi
-    if (( RVM_WITH_OPT_TEST_HARNESS )); then
-	TOP_LEVEL_SOURCES="${TOP_LEVEL_SOURCES} OptDummy.java OptTestHarness.java"
-    fi
-    TOP_LEVEL_SOURCES="${TOP_LEVEL_SOURCES} ${CONF_SPECIFIC_TOP_LEVEL_SOURCES}"
-    TOP_LEVEL_CLASSES="$(builtin echo ${TOP_LEVEL_SOURCES}| sed 's@\.java@.class@g')"
 
-    cat <<- EOF
-	if [[ -e $CLASSES_INVALID_STR ]]; then
-	    chdir $CLASSES_DIRECTORY_STR
-	    run rm -f $TOP_LEVEL_CLASSES
+    cat <<- 'EOF'
+	## Generate a list of the source files in RVM.classes that we'll
+	## feed to the Jikes compiler.
+	function get_top_level_sources () {
 	EOF
 
-    if [[ $host_jikes_version = 1.13 ]]; then
+    if (( all_sources_are_top_level )); then
+	echo '    find . -name \*.java -print'
+    else
+	echo '    echo "Dummy.java"'
+	if (( RVM_WITH_OPT_COMPILER )); then
+	    echo '    echo "OptDummy.java"'
+	fi
+	if (( RVM_WITH_OPT_TEST_HARNESS )); then
+	    echo '    echo "OptDummy.java OptTestHarness.java"'
+	fi
+	echo '    find gnu java -name \*.java -print'
+    fi
+    cat <<- EOF
+	    echo '${CONF_SPECIFIC_TOP_LEVEL_SOURCES}'
+	}
+	TOP_LEVEL_SOURCES="\$(get_top_level_sources)"
+
+	## Clean up the old build classes, if we have to.
+	## XXX TODO Make this consistent with the place above where we touch
+	## XXX $CLASSES_INVALID_STR
+	if [[ -e $CLASSES_INVALID_STR ]]; then
+	    if [[ "X${jikes_dependency_flag}" != X ]]; then
+	        TOP_LEVEL_CLASSES="\$(builtin echo \${TOP_LEVEL_SOURCES}| sed 's@\.java@.class@g')"
+	        run rm -f \$TOP_LEVEL_CLASSES
+	    else
+	        run-evaled find . -name '\*.class' \| \$XARGS rm -f
+	    fi
+	EOF
+
+#    if [[ $host_jikes_version = 1.13 ]]; then
+    if (( copy_MMTk_directories_too )); then
 	cat <<- EOF
-	     ## Jikes 1.13 does not have a -sourcepath argument.
-	    jikes_invocation="$JIKES_STR $JIKES_WARNING_FLAGS -g ${jikes_dependency_flag}  -classpath .:${ROOT_DIRECTORY_STR}/MMTk/src:rvmrt.jar -d . $TOP_LEVEL_SOURCES"
+	    ## Jikes 1.13 does not have a -sourcepath argument.  And if we copy
+	    ## the MMTk directories too, we do not need to use -sourcepath.
+	    jikes_invocation="$JIKES_STR $JIKES_WARNING_FLAGS -g ${jikes_dependency_flag}  -classpath .:${ROOT_DIRECTORY_STR}/MMTk/src:rvmrt.jar -d . \$TOP_LEVEL_SOURCES"
 	EOF
     else
 	cat <<- EOF
-	    jikes_invocation="$JIKES_STR $JIKES_WARNING_FLAGS -g ${jikes_dependency_flag} -sourcepath .:${ROOT_DIRECTORY_STR}/MMTk/src -classpath .:rvmrt.jar -d . $TOP_LEVEL_SOURCES"
+	    jikes_invocation="$JIKES_STR $JIKES_WARNING_FLAGS -g ${jikes_dependency_flag} -sourcepath .:${ROOT_DIRECTORY_STR}/MMTk/src -classpath .:rvmrt.jar -d . \$TOP_LEVEL_SOURCES"
 	EOF
     fi
 
@@ -2641,7 +2720,7 @@ EOF
 	    else
 	        status=\$?
 	        close_paren 'compilation FAILED'
-	        echo >&2 "\$ME: The Jikes compiler exited with status \${status} while we were building the source file(s): $TOP_LEVEL_SOURCES"
+	        echo >&2 "\$ME: The Jikes compiler exited with status \${status} while we were building the source file(s): \$TOP_LEVEL_SOURCES"
 	        echo >&2 "\$ME: We invoked the Jikes compiler in the directory $CLASSES_DIRECTORY_STR"
 	        echo >&2 "\$ME: With the command-line: \$jikes_invocation"
 	        exit \$status
