Expanded the error handling in case of trouble with the setting of the JIKES config variable.  Broken out into more functions for modularity.

diff --git a/rvm/bin/jconfigure b/rvm/bin/jconfigure
--- a/rvm/bin/jconfigure
+++ b/rvm/bin/jconfigure
@@ -39,7 +39,7 @@ fi
 ## In case of trouble, we exit with the triggering exit status (if invoked via 'set -e'.
 ## Exit status 33: Invalid arguments.
 declare -r -i Exit_Status_Bad_Args=33
-## Exit status 2: trouble (configuration, etc.)
+## Exit status 2: trouble (configuration problems, etc.)
 ## Exit status 1: misc. complaints.
 ##
 ## Exit status 111: The master "jbuild" script (generated by jconfigure) uses
@@ -388,10 +388,84 @@ function setSomeFromPath () {
     done
 }
 
-declare host_jikes_version=""	# empty string means unset.
+# If $host_jikes_version is the empty string, that means we have never 
+# tried to auto-detect the host's Jikes version.  We'll only auto-detect
+# the host's jikes version once.
+declare host_jikes_version=""
 
-function rationalize_config_file_settings () {
-    ## HOST_VM_TYPE: Valid working values: Sun, Kaffe
+function on_host_set_JIKES_test_Jikes_version () {
+        # Path for the Jikes java-to-byte-code compiler.  A necessary part of 
+    # the build process.  We only run JIKES on the host.
+    if [[ $CURRENT_CONFIG_FILE = $RVM_HOST_CONFIG ]]	\
+	&& ! [[ ${JIKES-} ]]				\
+	&& ! export JIKES=$(type -p jikes)
+    then
+	## Note: This is quite possibly bogus if we're reading in the target
+	## file instead of the host file, during a cross-build.
+	show_mesg "I can't find the Jikes java-to-byte-code compiler.  Please set the variable JIKES in $CURRENT_CONFIG_FILE or put an executable named \"jikes\" in your command search path"
+	trap '' EXIT
+	exit $Exit_Status_Bad_Args
+    fi
+
+    if [[ $CURRENT_CONFIG_FILE = $RVM_HOST_CONFIG ]] \
+	&& ! [[ $host_jikes_version ]]
+    then
+	## Check the Jikes version for the HOST.  We don't care 
+	## about the version of Jikes for the TARGET.
+	## Jikes 1.13 will exit with status 1 in response to "jikes -version",
+	## and spits the version message to stderr.
+	local jikes_msg		# If you combine the "local" declaration and 
+				# the assigment, it will always yield exit
+				# status zero, which is bad for us.
+	set +e 
+	jikes_msg="$(${JIKES} -version 2>&1)"
+	local -i status=$?
+	set -e
+#	echo "STATUS=$status"
+	if (( $status != 0 )) && (( $status != 1 )); then
+	    show_mesg >&2 "ERROR: I am having trouble running the Jikes compiler.  When I ran the command:"
+	    echo >&2 "	\"${JIKES} -version\""
+	    show_mesg_raw >&2 " that command exited with status code # $status and gave the message:"
+	    echo >&2 "	\"$jikes_msg\""
+	    show_mesg >&2 "This looks bad; I am giving up.  
+  The likely offending configuration file is  \"${CURRENT_CONFIG_FILE}\""
+	    exit 2
+	fi
+	case "$jikes_msg" in
+	    *"Version 1.13"*)
+		host_jikes_version=1.13 
+		;;
+
+	    *"Version 1.18"*)
+		host_jikes_version=1.18 ;;
+	    *"Version 1.19"*)
+		host_jikes_version=1.19 ;;
+	    "") show_mesg >&2 "WARNING: I can not get a version message from 
+  the Jikes java-to-byte-code compiler; something may be badly wrong.  
+  Continuing anyway.  I tried using this invocation of Jikes:
+   \"${JIKES} -version\"" 
+		host_jikes_version=UNAVAILABLE-OR-BAD
+		;;
+	    *)
+		show_mesg >&2 "WARNING: \"${JIKES}\" is a version of Jikes
+  that may not be able to compile Jikes RVM -- the known
+  good versions are 1.13, 1.18, and 1.19.  Your version 
+  gives me the message:"
+		## If we can't find a line with the string Version, then
+		## print the whole message.
+		( echo "$jikes_msg" | ${FGREP-fgrep} "Version" \
+		      || echo "\"$jikes_msg\"" ) >&2 
+		host_jikes_version=BAD
+		;;
+	esac
+    #     echo "JIKES VERSION: $jikes_version"
+    fi
+}
+
+
+
+function on_host_set_HOST_VM_variables () {
+        ## HOST_VM_TYPE: Valid working values: Sun, Kaffe
     ##			In-progress values: JikesRVM, gij
     : ${HOST_VM_TYPE=Sun}	# the default
 
@@ -465,6 +539,9 @@ function rationalize_config_file_settings () {
     if ! [[ ${TemplateExpander_HOST_VM_RT-} ]]; then
 	TemplateExpander_HOST_VM_RT="${HOST_VM_RT}"
     fi
+}
+
+function rationalize_config_file_settings () {
 
     if ! [[ ${HOST_JAVADOC-} ]] && [[ ${HOST_JAVA_HOME-} ]]; then
 	# The JDK Javadoc executable
@@ -472,53 +549,11 @@ function rationalize_config_file_settings () {
 	export HOST_JAVADOC="$HOST_JAVA_HOME/bin/javadoc"
     fi
 
-    # Path for the Jikes java-to-byte-code compiler.  A necessary part of 
-    # the build process.  We only run JIKES on the host.
-    if [[ $CURRENT_CONFIG_FILE = $RVM_HOST_CONFIG ]]	\
-	&& ! [[ ${JIKES-} ]]				\
-	&& ! export JIKES=$(type -p jikes)
-    then
-	## Note: This is quite possibly bogus if we're reading in the target
-	## file instead of the host file, during a cross-build.
-	show_mesg "I can't find the Jikes java-to-byte-code compiler.  Please set the variable JIKES in $CURRENT_CONFIG_FILE or put an executable named \"jikes\" in your command search path"
-	trap '' EXIT
-	exit $Exit_Status_Bad_Args
-    fi
+    on_host_set_HOST_VM_variables
 
     setSomeFromPath fgrep
 
-    if [[ $CURRENT_CONFIG_FILE = $RVM_HOST_CONFIG ]] \
-	&& ! [[ $host_jikes_version ]]
-    then
-	## Check the Jikes version for the HOST.  We don't care much
-	## about the version of Jikes for the non-host.
-	# Jikes 1.13 will exit with status 1 in response to "jikes -version".
-	local jikes_msg="$(${JIKES} -version 2>&1)" || :
-
-	case "$jikes_msg" in
-	    *"Version 1.13"*)
-		host_jikes_version=1.13 
-		;;
-
-	    *"Version 1.18"*)
-		host_jikes_version=1.18 ;;
-	    *"Version 1.19"*)
-		host_jikes_version=1.19 ;;
-	    "") show_mesg >&2 "I can not get a version message from the Jikes
-java-to-byte-code compiler; something may be badly wrong.  
-Continuing anyway." 
-		host_jikes_version=UNAVAILABLE
-		;;
-	    *)
-		show_mesg >&2 "You have a version of Jikes that may not be 
-able to compile Jikes RVM -- the known good versions are 
-1.13, 1.18, and 1.19. Your version is:"
-		echo "$jikes_msg" | ${FGREP-fgrep} Version >&2
-		host_jikes_version=BAD
-		;;
-	esac
-    #     echo "JIKES VERSION: $jikes_version"
-    fi
+    on_host_set_JIKES_test_Jikes_version
 
     ## HOST_JAVAC:
     ## The Java compiler.
@@ -4383,7 +4418,7 @@ then
 	    # Shell does not let us distinguish EOF from I/O errors.
 	    got_EOF=1
 	fi
-	# finish the line since our user did not type a newline' for us.
+	# finish the line since our user did not type a newline for us.
 	echo ""
 	if (( $got_EOF )); then
 	    show_mesg >&2 "Got EOF (End of File).  We will not write anything."
