Added debugging code.  Added a slightly better error message.

diff --git a/rvm/bin/runrvm b/rvm/bin/runrvm
--- a/rvm/bin/runrvm
+++ b/rvm/bin/runrvm
@@ -143,7 +143,10 @@ prog="$rvm_build/JikesRVM"
 shopt -s execfail
 
 declare -r syswrap="${rvm_build}/libsyswrap.so"
-if [[ -f ${syswrap} ]]; then
+if false; then
+    # This clause is here purely for debugging.
+    :
+elif [[ -f ${syswrap} ]]; then
     ## Turn on libsyswrap, which is to say, make sure that we will properly
     ## intercept the select() call.
     LD_PRELOAD="${syswrap}" exec "$prog" "${sys_args[@]}" "${classpath_arg[@]}" "${user_args[@]}"
@@ -151,5 +154,5 @@ else
     exec "$prog" "${sys_args[@]}" "${classpath_arg[@]}" "${user_args[@]}"
 fi
 declare -r -i status=$?
-echo >&2  "$ME: Failed to execute $prog; can't run Jikes RVM"
+echo >&2  "$ME: Failed to execute $prog (command status $status); can't run Jikes RVM"
 exit $status
